[package]

name = "Rust Playground"
version = "0.0.1"
authors = [ "Andi <andi@zerotired.com>" ]

[dependencies]
log = "0.3.*"
fern = "0.3.5"
time = "0.1.35"
ansi_term = "0.7.*"
threadpool = "1.0"
id3 = "0.1.10"

# nom = "^1.2.4"

futures = "0.1.*"

# options parsing
# https://github.com/kbknapp/clap-rs
clap = "2.0.*"

csv = "0.14.*"
rustc-serialize = "0.3.16"

dotenv = "0.8.0"
# dotenv_macros = "0.8.0"

# local stuff
# name_of_dependency = { path = "/path/to/dep" }

[[bin]]
name = "sanchez"
