[package]

name = "sanchez - http sniffer"
version = "0.0.1"
authors = [ "Andi <andi@zerotired.com>" ]

[dependencies]
log = "0.3.*"
fern = "0.3.5"
time = "0.1.25"
ansi_term = "0.6.*"
getopts = "0.2*"
pcap = "0.4.2"

[[bin]]
name = "sanchez"
