[package]

name = "CSV file importer"
version = "0.0.1"
authors = [ "Andi <andi@zerotired.com>" ]

[dependencies]
log = "0.3.*"
fern = "0.3.5"
time = "0.1.25"
ansi_term = "0.7"

# https://github.com/kbknapp/clap-rs
clap = "2.0.*"

csv = "0.14"
rustc-serialize = "0.3.16"

# local stuff
# name_of_dependency = { path = "/path/to/dep" }

[[bin]]
name = "sanchez"
